"""empty message

Revision ID: 51f493175827
Revises: 6461cd162ee5
Create Date: 2020-12-08 11:32:50.263585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f493175827'
down_revision = '6461cd162ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todo SET completed=False WHERE completed IS NULL;')
    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
